# Mobb/SonarQube Fixer on pull requests
# This workflow defines the needed steps to run SonarQube Code scan on every pull request and pass the results to Mobb Fixer.
#
# Secrets in use (add your missing ones):
# SONAR_TOKEN - your SonarQube user token (create it in your SonarQube or SonarCloud account)
# SONAR_HOST_URL - the URL of your SonarQube server (e.g., https://sonarcloud.io)
# MOBB_API_TOKEN - your Mobb user credentials (automatically set if you forked this repo via the Mobb app)
# GITHUB_TOKEN - automatically set by GitHub


name: "Mobb/SonarQube"

on:
  pull_request:
    branches: ["*"]

jobs:
  scan-and-fix:
    name: Scan with SonarQube and fix with Mobb
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      pull-requests: write
      statuses: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java (required for SonarScanner)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # Or '11', depending on your project

      - name: Run SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.1.0
        with:
          projectBaseDir: ./
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}  # Remove this line if using on-prem
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Download SonarQube findings
        run: |
            curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
            "${{ secrets.SONAR_HOST_URL }}/api/issues/search?organization=${{ secrets.SONAR_ORGANIZATION }}&projects=${{ secrets.SONAR_PROJECT_KEY }}&pullRequest=${{ github.event.pull_request.number }}&additionalFields=_all" \
            -o sonar_report.json

      - name: Archive report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sast-report
          path: sonar_report.json

      - name: Run Mobb on the findings and get fixes
        if: always()
        uses: mobb-dev/action/review@v1.1
        with:
          report-file: "sonar_report.json"
          api-key: ${{ secrets.MOBB_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          scanner: sonarqube
